---
title: "Covid-19 Colombia"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(RSocrata)
library(dygraphs)
library(xts)
library(incidence)
library(aTSA)
library(lmtest)
library(forecast)
library(dplyr)
library(seastests)
library(trend)
library(xtable)
library(graphics)
library(textreadr)
library(sf) #Contiene funciones para codificar datos espaciales.
library(ggplot2) #Sirve para crear graficos y mapear
library(tmap) #Importa mapas tematicos en los cuales se visualizan las distribuciones de datos espaciales.
library(tmaptools) #Conjunto de herramientas para leer y procesar datos espaciales.
library(leaflet) #Crea y personaliza mapas interactivos usando una biblioteca de JavaScript
library(rgdal) #Proporciona enlaces a la Biblioteca de abstraccion de datos 'geoespaciales' y acceso
#a las operaciones de proyeccion. 
library(sp) #Clases y metodos para datos espaciales.
library(readxl) #Importa archivos de excel a R.
library(mapview)

df.ins=read.csv("/Users/Carlos/Desktop/Ratoncita/Tesis Natalia/PRESENTACION TESIS/21dic.csv")
df.ins$fecha_inicio_sintomas <- as.Date(df.ins$fecha_inicio_sintomas,tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))
df.ins$fecha_de_notificaci_n <- as.Date(df.ins$fecha_de_notificaci_n, tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))
df.ins$fecha_muerte <- as.Date(df.ins$fecha_muerte, tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))
df.ins$fecha_recuperado <- as.Date(df.ins$fecha_recuperado, tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))
df.ins$fecha_reporte_web <- as.Date(df.ins$fecha_reporte_web, tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))
df.ins$fecha_diagnostico  <- as.Date(df.ins$fecha_diagnostico, tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))
#De la 11 a la 16 convierte en formato fecha corta.

df.ins$confirmados <- "Confirmados" #Crea una columna para tener un conteo de los confirmados diarios.

df.ins <- df.ins %>%
  dplyr::select(id_de_caso,
                ciudad_municipio_nom,
                fecha_inicio_sintomas,
                confirmados,
                fecha_de_notificaci_n,
                fecha_diagnostico,
                fecha_muerte,
                fecha_reporte_web,
                everything()) #Reorganiza la base.
inc.casos.colombia.confirmados <- incidence(df.ins$fecha_reporte_web,
  groups = df.ins$confirmados) #Hace un conteo de cantidad de 
mapa=readOGR("/Users/Carlos/Desktop/Ratoncita/Departamentos/depto.shp", stringsAsFactors=FALSE) #Exporta los datos para crear el mapa de Colombia dividido por departamentos
dashboard=st_read("/Users/Carlos/Desktop/Ratoncita/Departamentos/depto.shp",stringsAsFactors=FALSE) #Exporta las caracteristicas de cada departamento de Colombia
plot(mapa,main="COLOMBIA") #Crea el mapa de Colombia
str(mapa) #Muestra de forma compacta la estructura interna de un objeto.

####Correr codigo dash librerias y desde la linea 15 hasta la linea 18 para poder correr esto####
df.ins$codigo=NA #Crea una nueva columna sin datos.
df.ins$codigo=trunc(as.numeric(df.ins$ciudad_municipio)/1000) #A la columna creada le asigna el valor del codigo divipola 
#dividido por 1000, el cual es igual al codigo del dpto.
df.ins$recuperado[df.ins$recuperado=="N/A"]="N/A"
df.ins$recuperado=tolower(df.ins$recuperado)
tabla1=table(df.ins$codigo,df.ins$recuperado)
TOTAL=tabla1[,1]+tabla1[,2]+tabla1[,3]+tabla1[,4]
TOTAL=as.data.frame(TOTAL)
dashboard=arrange(dashboard, as.numeric(DPTO)) #Organiza de menor a mayor la base dashboard dependiendo del cod. de dpto.
rownames(TOTAL)=dashboard$NOMBRE_DPT
rownames(tabla1)=dashboard$NOMBRE_DPT
write.csv(tabla1, file="covid19.csv") #Guarda en un archivo .csv la tabla creada.
covid19=read.csv("/Users/Carlos/Desktop/Ratoncita/Tesis Natalia/PRESENTACION TESIS/covid19.csv") #Exporta el archivo creado anteriormente.
covid19=data.frame(covid19,TOTAL) #Concatena el archivo anterior con el total de contagiados.
names(covid19)=cbind("NOMBRE_DPT","CASOS ACTIVOS","FALLECIDOS","SIN REGISTROS","RECUPERADOS","TOTAL CONTAGIADOS") #Renombra las columnas.
dashboard=dashboard[,-1] #Elimina la primera columna de la base dashboard.
mapview(covid19[,2],layer.name="Total")
names(dashboard)
mapa_datos=inner_join(dashboard,covid19)#Une las bases dashboard y covid 19.
mapa_datos=mapa_datos[,-c(2:4)] #Elimina las columnas 2 a 4 de la base creada anteriormente.
tm_shape(mapa_datos)+
  tm_layout(title = "CASOS DE COVID-19 EN COLOMBIA. Realizado por: Natalia Vanegas")+
  tm_polygons("MAP_COLORS") #Crea el mapa estatico de Colombia dependiendo de los datos anteriores.

test_map=tmap_last() #Guarda el mapa.
tmap_save(test_map,"mapa.html",add.titles = TRUE) #Crea el archivo HTML del mapa dinamico.

```

```

Column {data-width=450} 
-----------------------------------------------------------------------
```{r}
mapview(mapa_datos)

```